source 'http://rubygems.org'
source 'http://gemcutter.org'
source 'http://gems.github.com'
require 'rubygems'
require 'csv'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '2.3.18'
gem 'sqlite3-ruby', :require => 'sqlite3'
